import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

test('macOS release workflow builds an unsigned arm64 DMG and publishes macos-v tags', () => {
  const repoRoot = new URL('../../../', import.meta.url);
  const workflow = readFileSync(new URL('.github/workflows/release-macos.yml', repoRoot), 'utf8');
  const script = readFileSync(new URL('apps/macos/scripts/build-dmg.sh', repoRoot), 'utf8');
  const guide = readFileSync(new URL('docs/MacOS-Client-Release.md', repoRoot), 'utf8');
  const xcodegenSha256 = '4d9e34b62172d645eed6457cac13fc222569974098ef4ee9c3368bedf0196806';

  assert.match(workflow, /workflow_dispatch/);
  assert.match(workflow, /version/);
  assert.match(workflow, /release_notes/);
  assert.match(workflow, /支持 Markdown 格式/);
  assert.match(workflow, /macos-v\$\{\{ inputs\.version \}\}/);
  assert.match(workflow, /Xcode 27/);
  assert.match(workflow, /runs-on:\s+xcode-27\s*$/m);
  assert.doesNotMatch(workflow, /runs-on:\s+macos-26/);
  assert.match(workflow, /scripts\/build-dmg\.sh/);
  assert.match(workflow, /id:\s+checkout\s*$/m);
  assert.match(workflow, /checkout_commit:\s+\$\{\{ steps\.checkout\.outputs\.commit \}\}/);
  assert.match(workflow, /TARGET_COMMIT:\s+\$\{\{ needs\.build\.outputs\.checkout_commit \}\}/);
  assert.match(workflow, /--target "\$TARGET_COMMIT"/);
  assert.match(workflow, /CURRENT_REF:\s+\$\{\{ github\.ref_name \}\}/);
  assert.match(workflow,/"\$CURRENT_REF"/);
  assert.doesNotMatch(workflow, /echo[^\n]*github\.ref_name/);
  assert.match(workflow, /XCODEGEN_SHA256:\s*"4d9e34b62172d645eed6457cac13fc222569974098ef4ee9c3368bedf0196806"/);
  assert.match(workflow, /shasum -a 256 -c/);
  assert.match(workflow, /Qiankunjie\.dmg/);
  assert.match(workflow, /macos-release\/Qiankunjie\.dmg/);
  assert.match(workflow, /Qiankunjie-\$\{VERSION\}-arm64\.dmg/);
  assert.match(workflow, /macos-release\/Qiankunjie-\$\{VERSION\}-arm64\.dmg/);
  assert.match(workflow, /Qiankunjie\.dmg\.sha256/);
  assert.match(workflow, /macos-release\/Qiankunjie\.dmg\.sha256/);
  assert.match(workflow, /macos-release\/Qiankunjie-\$\{VERSION\}-arm64\.dmg\.sha256/);
  assert.match(workflow, /contents:\s+read/);
  assert.match(workflow, /contents:\s+write/);
  assert.match(workflow, /ref:\s+master/);
  assert.doesNotMatch(workflow, /Sparkle/i);
  assert.match(script, /CODE_SIGNING_ALLOWED=NO/);
  assert.match(script, /hdiutil verify/);
  assert.match(script, /lipo -archs/);
  assert.match(script, /\.sha256/);
  assert.match(guide, /Gatekeeper/);
  assert.match(guide, /macOS 27/);
  assert.match(guide, /Apple Silicon/);
  assert.match(guide, /更新失败/);
  assert.match(guide, /无证书/);
  assert.doesNotMatch(workflow, /codesign|notarytool|stapler/);
});
